import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Building2,
  CheckCircle2,
  ClipboardList,
  FileCog,
  FileText,
  FolderOpen,
  Settings,
  ShieldCheck,
  ShoppingCart,
  UserCog,
  Users,
} from "lucide-react";
import type { NavItem, PageKey, CompanyUser, NotaryUser } from "./types";

export const navItems: NavItem[] = [
  { key: "dashboard", label: "Dashboard", icon: BarChart3 },
  { key: "usersCompanies", label: "Users Management", icon: Users },
  { key: "orders", label: "Orders Management", icon: ShoppingCart },
  { key: "documents", label: "Documents", icon: FileText },
  { key: "analytics", label: "Analytics", icon: Activity },
  { key: "settings", label: "Settings", icon: Settings },
];

export const pageGroups: Record<PageKey, NavItem["key"]> = {
  dashboard: "dashboard",
  usersCompanies: "usersCompanies",
  usersNotaries: "usersCompanies",
  companyDetails: "usersCompanies",
  notaryProfile: "usersCompanies",
  orders: "orders",
  orderDetails: "orders",
  documents: "documents",
  documentView: "documents",
  analytics: "analytics",
  settings: "settings",
  notifications: "settings",
};

export type MetricCard = {
  title: string;
  value: string;
  note?: string;
  tone?: "blue" | "green" | "amber" | "slate";
  icon: LucideIcon;
};

export const dashboardMetrics: MetricCard[] = [
  { title: "Total Title Companies", value: "142", note: "+12%", tone: "blue", icon: Building2 },
  { title: "Total Notaries", value: "1,208", note: "+4%", tone: "blue", icon: UserCog },
  { title: "Total Orders", value: "8,492", tone: "slate", icon: ClipboardList },
  { title: "Orders Pending Approval", value: "28", note: "Alert", tone: "amber", icon: FileCog },
  { title: "Completed Orders", value: "7,814", note: "92%", tone: "green", icon: CheckCircle2 },
];

export const analyticsMetrics: MetricCard[] = [
  { title: "Total Orders", value: "2,482", note: "+12%", tone: "blue", icon: ClipboardList },
  { title: "Completed", value: "1,845", tone: "blue", icon: CheckCircle2 },
  { title: "Pending Orders", value: "485", tone: "amber", icon: FolderOpen },
  { title: "Active Notaries", value: "124", tone: "slate", icon: UserCog },
  { title: "Title Companies", value: "86", tone: "slate", icon: Building2 },
];

export const companyRows: CompanyUser[] = [
  {
    id: "COMP-1",
    initials: "ST",
    color: "bg-[#DCE7FF] text-[#3165CF]",
    companyName: "Summit Title",
    contactPerson: "Jane Smith",
    businessEmail: "jane.smith@summittitle.com",
    phone: "(555) 123-4567",
    status: "Active",
    createdDate: "Feb 28, 2026",
    address: "123 Main St, Austin, TX 78701",
    contactEmail: "jane.smith@summittitle.com",
    userName: "janesmith",
  },
  {
    id: "COMP-2",
    initials: "BA",
    color: "bg-[#FFE2D3] text-[#C66B33]",
    companyName: "Blue Anchor LLC",
    contactPerson: "Robert Chen",
    businessEmail: "r.chen@blueanchor.io",
    phone: "(555) 987-6543",
    status: "Pending",
    createdDate: "Feb 28, 2026",
    address: "456 Ocean Dr, Miami, FL 33139",
    contactEmail: "r.chen@blueanchor.io",
    userName: "robertchen",
  },
  {
    id: "COMP-3",
    initials: "ET",
    color: "bg-[#E9EEF6] text-[#69778E]",
    companyName: "Elite Trust",
    contactPerson: "Amanda Waller",
    businessEmail: "awaller@elitetrust.com",
    phone: "(555) 444-3322",
    status: "Inactive",
    createdDate: "Feb 28, 2026",
    address: "789 Capitol Way, Washington, DC 20001",
    contactEmail: "awaller@elitetrust.com",
    userName: "amandawaller",
  },
  {
    id: "COMP-4",
    initials: "HS",
    color: "bg-[#DCE7FF] text-[#3165CF]",
    companyName: "Horizon Settlements",
    contactPerson: "Michael Scott",
    businessEmail: "m.scott@horizonsettle.com",
    phone: "(555) 888-9900",
    status: "Active",
    createdDate: "Feb 28, 2026",
    address: "1725 Slough Ave, Scranton, PA 18505",
    contactEmail: "m.scott@horizonsettle.com",
    userName: "michaelscott",
  },
  {
    id: "COMP-5",
    initials: "VE",
    color: "bg-[#E2FBE9] text-[#2F9E44]",
    companyName: "Vanguard Escrow",
    contactPerson: "Sarah Jenkins",
    businessEmail: "s.jenkins@vanguardescrow.com",
    phone: "(555) 222-1133",
    status: "Active",
    createdDate: "Feb 27, 2026",
    address: "500 Financial Way, San Francisco, CA 94111",
    contactEmail: "s.jenkins@vanguardescrow.com",
    userName: "sarahjenkins",
  },
  {
    id: "COMP-6",
    initials: "LC",
    color: "bg-[#FFF4E6] text-[#D9480F]",
    companyName: "Landmark Closings",
    contactPerson: "David Miller",
    businessEmail: "d.miller@landmarkclosings.com",
    phone: "(555) 777-6655",
    status: "Active",
    createdDate: "Feb 26, 2026",
    address: "100 Landmark Blvd, Dallas, TX 75201",
    contactEmail: "d.miller@landmarkclosings.com",
    userName: "davidmiller",
  },
  {
    id: "COMP-7",
    initials: "PS",
    color: "bg-[#F3F0FF] text-[#7048E8]",
    companyName: "Prime Settlement",
    contactPerson: "Sophia Lopez",
    businessEmail: "sophia.l@primesettlement.com",
    phone: "(555) 333-8877",
    status: "Pending",
    createdDate: "Feb 25, 2026",
    address: "88 Pine St, New York, NY 10005",
    contactEmail: "sophia.l@primesettlement.com",
    userName: "sophialopez",
  },
  {
    id: "COMP-8",
    initials: "AT",
    color: "bg-[#E3FAF9] text-[#0C8599]",
    companyName: "Apex Title & Escrow",
    contactPerson: "James Wilson",
    businessEmail: "j.wilson@apextitle.com",
    phone: "(555) 999-1122",
    status: "Active",
    createdDate: "Feb 24, 2026",
    address: "250 Apex Tower, Denver, CO 80202",
    contactEmail: "j.wilson@apextitle.com",
    userName: "jameswilson",
  },
  {
    id: "COMP-9",
    initials: "KC",
    color: "bg-[#FFF0F6] text-[#D6336C]",
    companyName: "Keystone Closing",
    contactPerson: "Emily Davis",
    businessEmail: "emily@keystoneclosing.com",
    phone: "(555) 444-9988",
    status: "Active",
    createdDate: "Feb 23, 2026",
    address: "300 Keystone Way, Philadelphia, PA 19103",
    contactEmail: "emily@keystoneclosing.com",
    userName: "emilydavis",
  },
  {
    id: "COMP-10",
    initials: "NW",
    color: "bg-[#F1F3F5] text-[#495057]",
    companyName: "Northway Title",
    contactPerson: "Sarah J. Miller",
    businessEmail: "sarah.m@northway.com",
    phone: "(555) 111-2222",
    status: "Active",
    createdDate: "Feb 22, 2026",
    address: "900 Northway Parkway, Chicago, IL 60611",
    contactEmail: "sarah.m@northway.com",
    userName: "sarahmiller",
  },
  {
    id: "COMP-11",
    initials: "LT",
    color: "bg-[#DCE7FF] text-[#3165CF]",
    companyName: "Liberty Title Group",
    contactPerson: "George Washington",
    businessEmail: "g.washington@libertytitle.com",
    phone: "(555) 777-8888",
    status: "Inactive",
    createdDate: "Feb 21, 2026",
    address: "1776 Independence Ave, Philadelphia, PA 19106",
    contactEmail: "g.washington@libertytitle.com",
    userName: "georgewashington",
  },
  {
    id: "COMP-12",
    initials: "PT",
    color: "bg-[#FFE2D3] text-[#C66B33]",
    companyName: "Pioneer Title",
    contactPerson: "Clara Barton",
    businessEmail: "c.barton@pioneertitle.com",
    phone: "(555) 333-4444",
    status: "Active",
    createdDate: "Feb 20, 2026",
    address: "1881 Red Cross Lane, Washington, DC 20006",
    contactEmail: "c.barton@pioneertitle.com",
    userName: "clarabarton",
  },
];

export const notaryRows: NotaryUser[] = [
  {
    id: "NOT-1",
    initials: "SH",
    color: "bg-[#DCE7FF] text-[#3165CF]",
    fullName: "Sarah Harrison",
    specialty: "Residential Specialist",
    email: "s.harrison@legalmail.com",
    phone: "(555) 124-5567",
    license: "NY-882910",
    status: "Active",
    createdDate: "Oct 12, 2023",
    expiry: "12/31/2026",
    serviceArea: "New York, NY",
    userName: "sarahharrison",
  },
  {
    id: "NOT-2",
    initials: "JM",
    color: "bg-[#FFE2D3] text-[#C66B33]",
    fullName: "James Miller",
    specialty: "Commercial Notary",
    email: "j.miller@proclosing.net",
    phone: "(555) 901-2234",
    license: "TX-445012",
    status: "Pending",
    createdDate: "Dec 01, 2023",
    expiry: "06/30/2027",
    serviceArea: "Houston, TX",
    userName: "jamesmiller",
  },
  {
    id: "NOT-3",
    initials: "ML",
    color: "bg-[#E9EEF6] text-[#69778E]",
    fullName: "Maria Lopez",
    specialty: "Bilingual / Escrow",
    email: "m.lopez@globale.com",
    phone: "(555) 345-1289",
    license: "FL-110293",
    status: "Inactive",
    createdDate: "Aug 22, 2023",
    expiry: "09/15/2026",
    serviceArea: "Miami, FL",
    userName: "marialopez",
  },
  {
    id: "NOT-4",
    initials: "DK",
    color: "bg-[#DCE7FF] text-[#3165CF]",
    fullName: "David Kim",
    specialty: "Title Agent",
    email: "d.kim@proclosing.net",
    phone: "(555) 778-4432",
    license: "CA-909281",
    status: "Active",
    createdDate: "Nov 15, 2023",
    expiry: "03/22/2028",
    serviceArea: "Los Angeles, CA",
    userName: "davidkim",
  },
  {
    id: "NOT-5",
    initials: "EM",
    color: "bg-[#DFE6FF] text-[#5B6AAE]",
    fullName: "Emily Davis",
    specialty: "eNotary / Remote",
    email: "emily.davis@notaryonline.org",
    phone: "(555) 234-5678",
    license: "OH-883344",
    status: "Active",
    createdDate: "Jan 12, 2024",
    expiry: "05/18/2027",
    serviceArea: "Columbus, OH",
    userName: "emilydavis",
  },
  {
    id: "NOT-6",
    initials: "MW",
    color: "bg-[#FFE1D2] text-[#C87846]",
    fullName: "Marcus Washington",
    specialty: "Loan Signing Agent",
    email: "m.washington@signingpro.com",
    phone: "(555) 876-5432",
    license: "VA-112233",
    status: "Active",
    createdDate: "Feb 05, 2024",
    expiry: "11/30/2026",
    serviceArea: "Richmond, VA",
    userName: "marcuswashington",
  },
  {
    id: "NOT-7",
    initials: "SR",
    color: "bg-[#DCE7FF] text-[#4259B2]",
    fullName: "Sarah Rodriguez",
    specialty: "Bilingual Notary",
    email: "s.rodriguez@valleydoc.net",
    phone: "(555) 345-6789",
    license: "AZ-998877",
    status: "Pending",
    createdDate: "Mar 10, 2024",
    expiry: "08/14/2028",
    serviceArea: "Phoenix, AZ",
    userName: "sarahrodriguez",
  },
  {
    id: "NOT-8",
    initials: "JC",
    color: "bg-[#E2FBE9] text-[#2F9E44]",
    fullName: "John Carter",
    specialty: "Mobile Notary Public",
    email: "j.carter@cartersign.com",
    phone: "(555) 765-4321",
    license: "IL-554433",
    status: "Active",
    createdDate: "Apr 22, 2024",
    expiry: "10/01/2027",
    serviceArea: "Chicago, IL",
    userName: "johncarter",
  },
  {
    id: "NOT-9",
    initials: "AT",
    color: "bg-[#F3F0FF] text-[#7048E8]",
    fullName: "Alex Thompson",
    specialty: "Commercial Closings",
    email: "a.thompson@apexsigning.com",
    phone: "(555) 456-7890",
    license: "CO-776655",
    status: "Inactive",
    createdDate: "May 15, 2024",
    expiry: "02/28/2026",
    serviceArea: "Denver, CO",
    userName: "alexthompson",
  },
  {
    id: "NOT-10",
    initials: "LW",
    color: "bg-[#E3FAF9] text-[#0C8599]",
    fullName: "Lisa Wong",
    specialty: "Escrow Signing Agent",
    email: "lisa.wong@pacificescrow.net",
    phone: "(555) 987-1234",
    license: "WA-443322",
    status: "Active",
    createdDate: "Jun 02, 2024",
    expiry: "07/19/2027",
    serviceArea: "Seattle, WA",
    userName: "lisawong",
  },
  {
    id: "NOT-11",
    initials: "RB",
    color: "bg-[#FFF0F6] text-[#D6336C]",
    fullName: "Robert Brown",
    specialty: "Residential & Refi",
    email: "r.brown@metroclosings.com",
    phone: "(555) 567-8901",
    license: "GA-665544",
    status: "Active",
    createdDate: "Jul 18, 2024",
    expiry: "12/15/2028",
    serviceArea: "Atlanta, GA",
    userName: "robertbrown",
  },
  {
    id: "NOT-12",
    initials: "NK",
    color: "bg-[#F1F3F5] text-[#495057]",
    fullName: "Nancy Kelly",
    specialty: "General Notary Public",
    email: "n.kelly@kellysigning.com",
    phone: "(555) 678-9012",
    license: "MA-221100",
    status: "Pending",
    createdDate: "Aug 09, 2024",
    expiry: "04/30/2027",
    serviceArea: "Boston, MA",
    userName: "nancykelly",
  },
];

export const orderRows = [
  ["#ORD-90212", "Northway Holdings", "NH", "Jane Simmons", "123 Maple St\nAustin, TX", "Oct 24,\n2023", "Assigned", "jane"],
  ["#ORD-90208", "Acme Title Co.", "AT", "Unassigned", "456 Oak Ave\nDallas, TX", "Oct 22,\n2023", "Received", "none"],
  ["#ORD-88421", "Capital Escrow", "CE", "Mark Evans", "789 Pine Rd\nHouston, TX", "Oct 18,\n2023", "Completed", "mark"],
] as const;

export const documentRows = [
  ["Closing_Disclosure_Fina...", "#ORD-882190", "TITLE COMPANY", "Oct 24, 2023", "1.2 MB", "Approved"],
  ["Wire_Instructions_A-B.pdf", "#ORD-991022", "NOTARY", "Oct 23, 2023", "450 KB", "Pending"],
  ["Insurance_Binder_Proof....", "#ORD-771234", "BUYER", "Oct 22, 2023", "2.4 MB", "Rejected"],
  ["Title_Search_Report.pdf", "#ORD-881552", "TITLE COMPANY", "Oct 20, 2023", "3.1 MB", "Approved"],
] as const;

export const quickActions = [
  { title: "Add User", description: "Create new internal or partner accounts", icon: UserCog, tone: "blue" },
  { title: "Assign Orders", description: "Route pending files to available notaries", icon: ClipboardList, tone: "slate" },
  { title: "Approve Documents", description: "Verify and sign-off on 28 pending items", icon: ShieldCheck, tone: "amber" },
] as const;

export const teamMembers = [
  ["SM", "bg-[#DCE7FF] text-[#4259B2]", "Sarah J. Miller", "sarah.m@northway.com", "Senior Escrow Officer"],
  ["MC", "bg-[#DFE6FF] text-[#5B6AAE]", "Marcus Chen", "m.chen@northway.com", "Director of Operations"],
  ["ER", "bg-[#FFE1D2] text-[#C87846]", "Elena Rodriguez", "elena.r@northway.com", "Founder"],
] as const;

export const recentOrders = [
  ["#ORD-90212", "In Progress", "Mar 20, 2026"],
  ["#ORD-90208", "Approved", "Mar 15, 2026"],
  ["#ORD-88421", "Completed", "Feb 24, 2026"],
] as const;

export const assignedOrders = [
  ["#ORD-90212", "In Progress", "Oct 24, 2023"],
  ["#ORD-90208", "Approved", "Oct 22, 2023"],
  ["#ORD-88421", "Completed", "Oct 18, 2023"],
] as const;

export const uploadActivity = [
  ["Commission_Certificate.pdf", "Uploaded Sep 12, 2023"],
  ["Background_Check_2023.pdf", "Uploaded Aug 15, 2023"],
] as const;

export const orderTimeline = [
  ["Order created by System", "Oct 20, 2024 • 09:45 AM", "blue"],
  ["Notary John Doe assigned", "Oct 21, 2024 • 02:20 PM", "slate"],
  ["Documents uploaded by John Doe", "Oct 24, 2024 • 04:15 PM", "green"],
] as const;

export const documentTimeline = [
  ["File uploaded by Northway Holdings", "Oct 24, 10:15 AM", "blue"],
  ["Automated scan complete - No errors found", "Oct 24, 10:16 AM", "slate"],
  ["Assigned to Admin Review", "Oct 24, 10:20 AM", "slate"],
] as const;

export const assignableNotaries = [
  ["Sarah Jenkins", "Austin, TX • 4.9 Rating", "Active"],
  ["Marcus Thorne", "Round Rock, TX • 4.7 Rating", "Verified"],
  ["Elena Rodriguez", "Cedar Park, TX • 5.0 Rating", "Active"],
] as const;

export const stepItems = ["Received", "Assigned", "Under Review", "Approved", "Completed"] as const;

export const statusConfig = {
  Active: "bg-[#EEF9F0] text-[#2F9E54]",
  Pending: "bg-[#FFF4DB] text-[#C79016]",
  Inactive: "bg-[#E9EEF6] text-[#6A7280]",
  Approved: "bg-[#E8F8EA] text-[#2C9A4D]",
  Rejected: "bg-[#FDE8E7] text-[#D25753]",
  Assigned: "bg-[#DFEAFE] text-[#2E68CF]",
  Received: "bg-[#EDF1F6] text-[#7B8492]",
  Completed: "bg-[#DCF9E5] text-[#3DAE66]",
  "In Progress": "bg-[#E7EEFF] text-[#336DDA]",
  Verified: "bg-[#DFEAFE] text-[#2E68CF]",
  "Pending Review": "bg-[#FFE8D8] text-[#CE7E3B]",
  "Under Review": "bg-[#E7EEFF] text-[#336DDA]",
} as const;

export const profileGradients = {
  jane:
    "bg-[radial-gradient(circle_at_35%_30%,#f0d0bc_0_12%,transparent_13%),radial-gradient(circle_at_42%_34%,#3d2c30_0_11%,transparent_12%),radial-gradient(circle_at_55%_34%,#3d2c30_0_10%,transparent_11%),radial-gradient(circle_at_50%_70%,#d48c6e_0_19%,transparent_20%),linear-gradient(180deg,#9fd3ff_0%,#dfeeff_100%)]",
  alex:
    "bg-[radial-gradient(circle_at_48%_28%,#f2c6a9_0_9%,transparent_10%),radial-gradient(circle_at_47%_24%,#0f172a_0_17%,transparent_18%),radial-gradient(circle_at_50%_64%,#5973cf_0_20%,transparent_21%),linear-gradient(180deg,#0d172d_0%,#2c5eb8_100%)]",
  mark:
    "bg-[radial-gradient(circle_at_48%_28%,#f0c4a5_0_9%,transparent_10%),radial-gradient(circle_at_47%_24%,#211a1a_0_17%,transparent_18%),radial-gradient(circle_at_50%_64%,#253858_0_20%,transparent_21%),linear-gradient(180deg,#131a28_0%,#40598d_100%)]",
};
